name: 'Chromatic Publish Storybook'

# Event for the workflow
on: 
  push:
    branches: ['main']

jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    # Job steps
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js environment ${{ matrix.node-version }} version
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      #Adds Chromatic as a step in the workflow
      - name: Publish UI-Kit to Chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: '../../packages/ui-kit'